### ISSUE TITLE
Task List for 1.19

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#803]
This is a list of features to be added over time in the midst of 1.19, this issue will be updated and progress over time.

**ReqList:** 
- [x] Fix Vine placement : https://github.com/VolmitSoftware/Iris/issues/815
- [x] Fix Skulk placement when doing Paint
- [x] **MEMORY LEAK** Pregen
- [x] **MEMORY LEAK** Active
- [x] Enhancement/Fix Objects in caves
- [x] Loot not propagating in pregenned world chests
- [x] Add a Stronghold system but for every/any structure (ancient city etc...)
- [x] Be able to specify a blacklist / Whitelist for decorators ie: i want fields of grass but only on concrete powder
- [x] Fix / Reimplement the palette system: https://github.com/VolmitSoftware/Iris/issues/808 
- [x] Cave Blockieness look into this / verify its fixed Status: https://github.com/VolmitSoftware/Iris/issues/805
- [x] Fix Jigsaw Strongholds, they generate like half the time.
- [x] When 1.19.1 comes out be ready to update

[Ill update this as i need things for a weekly venture]
### Alternatives

If this could not be implemented I would... No its going to be implemented 🔪 🩸

**Comment by Vatuu** [comment]
Done!
